XLO/XLO/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


from . import views as home_views

urlpatterns = [
    url(r'^$', home_views.home, name='home_page'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/', include('profiles.urls')),
    url(r'^ads/', include('ads.urls')), 
    url(r'^auth/', include('registration.backends.simple.urls')),
    url(r'^message/', include('message.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

XLO/ads/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.all_ads,name="all_ads"),
    url(r'^(?P<ad_id>[0-9]+)/details/$', views.details,name='ads_details'),
    url(r'^create/$', views.create,name="ads_create"),
    url(r'^(?P<ad_id>[0-9]+)/edit/$', views.edit,name='ads_edit'),    
]

XLO/ads/models.py
# coding=utf-8
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

class Advertisement(models.Model):
    CATEGORIES = (
        ("Art sp","Artykuly spozywcze"),
        ("RTV AGD","RTV AGD"),
        ("inne","inne")
    )
    title = models.CharField(verbose_name = 'Tytuł ogłoszenia',
                             max_length = 70)
    price = models.CharField(max_length=20)
    content = models.TextField(verbose_name = 'Treść ogłoszenia')

    photo = models.ImageField(verbose_name='Zdjęcie',
                               blank = True, 
                               null = True,
                               upload_to='ogloszenia/photos')

    profile = models.ForeignKey('profiles.UserProfile')
    create_date = models.DateField(auto_now_add=True)
    category = models.CharField(verbose_name = 'Kategoria',
                                     max_length=20, 
                                     choices=CATEGORIES) 
    active = models.BooleanField(default=False, verbose_name='Czy aktywne?')
    def __unicode__(self):
    	return self.title

    def get_absolute_url(self):
        return reverse('ads.views.details', kwargs={'ad_id': self.id})

    def get_absolute_edit_url(self):
        return reverse('ads.views.edit', kwargs={'ad_id': self.id})

    def get_photo_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url
        else:
            return '/static/images/no_photo.png'

XLO/profiles/models.py
# coding=utf-8

from django.db import models

from django.db.models.signals import post_save
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User

# User Profile class extending django.contrib.auth.models.User
class UserProfile(models.Model):

    DORM_CHOICES = (
      ('mikrus', 'Mikrus'),
      ('ustronie', 'Ustronie'),
      ('riviera', 'Riviera'),
    )
    dorm = models.CharField(verbose_name = 'Akademik',
                            max_length = 16,
                            choices=DORM_CHOICES)

    avatar = models.ImageField(verbose_name='Avatar',
                               blank = True, 
                               null = True,
                               upload_to='profiles/avatars')

    name = models.CharField(verbose_name = 'Imię i nazwisko',
                            max_length = 32,
                            blank = True,
                            null = True)

    phone = models.CharField(verbose_name = 'Nr telefonu',
                             max_length = 9,
                             blank = True,
                             null = True)

    user = models.OneToOneField(User)


    class Meta:
      verbose_name_plural = 'Profile użytkowników'

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('profiles.views.detail_view', kwargs={'user_name': self.user.username})

    def get_avatar_url(self):
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        else:
            return '/static/images/default_profile_image.png'

    

# Creates User Profile (when new user instance is created) by post_save signal
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

# link registering new users with creating profiles for them
post_save.connect(create_user_profile, sender=User)

XLO/ads/forms.py
from django import forms
from .models import Advertisement

class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        exclude = ['profile']

XLO/ads/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required

from .models import Advertisement
from .forms import AdvertisementForm

from message.forms import MessageForm

def details(request, ad_id):
	#profile = request.user.userprofile
	ad=Advertisement.objects.get(id=ad_id)
	context = {'ad' : ad}
	
	context['contact_form'] = MessageForm()
	return render(request, 'ads/details.html', context)

@login_required         
def create(request):
	profile = request.user.userprofile

	if request.POST:
		ad_form = AdvertisementForm(request.POST or None, request.FILES)
		if ad_form.is_valid():
			adver = ad_form.save(commit=False)
			adver.profile = profile
			adver.save()
			return redirect(profile)
	else:
		ad_form = AdvertisementForm()

	context_dict = {'form': ad_form}
	return render(request, 'ads/create.html', context_dict)


def all_ads(request):
    ads_list = Advertisement.objects.filter(active=True)
    context =  {'ads_list': ads_list}
    return render(request, 'ads/list.html', context)



def edit(request, ad_id):
	profile = request.user.userprofile
	ad=Advertisement.objects.get(id=ad_id)
	if request.POST:
		ad_form = AdvertisementForm(request.POST, request.FILES, instance=ad)
		if ad_form.is_valid():
			ad_form.save()
			return redirect(ad)
	else:
		ad_form = AdvertisementForm(instance = ad)
	context = {'ad' : ad, 'form' : ad_form}
	return render(request, 'ads/edit.html', context)

XLO/templates/ads/create.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Utwórz ogłoszenie{% endblock %}

{% block content %}
<div class="container" style="margin-bottom: 40px;">
	<div class="row">
		<div class="col-sm-12 text-center">
			<h1>Utwórz ogłoszenie</h1>
		</div>
	</div>
</div>

<!-- FORM ERRORS -->
{% if form.errors %}
	{% for field, errors in form.errors.items %}
		{% for error in errors %}
		    <div class="row">
		        <div class="text-center alert alert-danger">
		            <strong>{{ error }}</strong>
		        </div>
		    </div>
		{% endfor %}
	{% endfor %}
{% endif %}

<!-- REGISTRATION FORM FROM CONTEXT -->
<form method="POST" action="" enctype="multipart/form-data" role="form" class="form-horizontal">
    {% csrf_token %}
    {% for field in form %}
    	<div class="form-group">
    		<label class="control-label col-sm-5" for="{{ field.id_for_label }}">{{ field.label }}</label>
    		<div class="col-sm-2">
    			{% if field.html_name == "photo" %}
    				{{ field | add_class:"file" }}
    			{% else %}
	    			{{ field | add_class:"form-control" }}
	    		{% endif %}
	    	</div>
	    </div>
    {% endfor %}
    <div class="form-group">
	<div class="col-sm-offset-5 col-sm-10">
		<button type="submit" class="btn btn-default">Dodaj</button>
	</div>
</div>
</form>
{% endblock %}

XLO/templates/ads/details.html
{% extends "base.html" %}
{% load static widget_tweaks %}

{% block title %}
	Tytuł : {{ ad.title }}
{% endblock %}

{% block content %}
	<div class="container" style="margin-bottom: 60px;">
		<div class="row ogloszenie-title">
			<div class="col-sm-6 col-sm-offset-3">
				<h2>{{ ad.title }}</h2>
				<p>Zamieszczono: {{ ad.create_date }}</p>
				{% if user.is_authenticated and request.user.userprofile == ad.profile %}
	  				<a href="{{ ad.get_absolute_edit_url }} "><span class="glyphicon glyphicon-file"></span> Edytuj ogłoszenie</a>
	  			{% endif %}
			</div>
		</div>
		
		<div class="row ogloszenie-properties">
			<p class="col-sm-3 col-sm-offset-3">Akademik: </p>
			<p class="col-sm-3 text-right"><strong>{{ ad.profile.get_dorm_display }}</strong></p>
		</div>
		<div class="row ogloszenie-properties">
			<p class="col-sm-3 col-sm-offset-3">Dodane przez: </p>
			<p class="col-sm-3 text-right"><strong>{{ ad.profile.user.username }}</strong></p>
		</div>
		<div class="row ogloszenie-properties">
			<p class="col-sm-3 col-sm-offset-3">Cena: </p>
			<p class="col-sm-3 text-right"><span class="ogloszenie-price">{{ ad.price }}</span></p>
		</div>
		<div class="row ogloszenie-content">
			<p class="col-sm-6 col-sm-offset-3">{{ ad.content }}</p>
		</div>             
	  	<div class="row ogloszenie-photo">
	  		<div class="col-sm-6 col-sm-offset-3 text-center">
				<img src="{{ ad.get_photo_url }}" />
			</div>
		</div>
        <br />
		

		{% block contact_form %}
        {% if not user.is_authenticated %}
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3 text-center">
                <strong>Zaloguj się, aby wysłać pytanie o przedmiot.</strong>
            </div>
        </div>
        {% else %}    
			{% ifnotequal request.user ad.profile.user %}
			<div class="row">
			<div class="col-sm-2 col-sm-offset-5">
		     <a href="#reply" class="btn btn-info" data-toggle="collapse">Napisz wiadomość</a>
		 	</div>
		 	</div>
			<div id="reply" class="collapse">

			<form method="POST" action="/message/create_message" enctype="multipart/form-data" role="form" class="form-horizontal">
			    {% csrf_token %}
			    {% for field in contact_form.visible_fields %}
			    	<div class="form-group">
                        <div class="row">
                            <div class="col-sm-offset-3 col-sm-6"><label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label></div>
                        </div>
                        <div class="row">
			    		    <div class="col-sm-offset-3 col-sm-6">
				    		    {{ field | add_class:"form-control"}} 
				    	    </div>
                        </div>
				    </div>
			    {% endfor %}
			   


		    	<div class="form-group">
	    		<div class="col-sm-2">
		    		<input type="hidden" name="advert" value = "{{ad.id}}">	    		
		    	</div></div>
			    <div class="form-group">
                <div class="row">
				<div class="col-sm-offset-3 col-sm-6 text-center">
					<button type="submit" class="btn btn-info">
						<span class="glyphicon glyphicon-envelope"></span> Wyślij
					</button>
				</div>
                </div>
                </div>
			
			</form>
			</div>
			{% endifnotequal %}
        {% endif %}
		{% endblock contact_form %}  
	</div>
{% endblock %}

XLO/templates/ads/edit.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Utwórz ogłoszenie{% endblock %}

{% block content %}
<div class="container" style="margin-bottom: 40px;">
	<div class="row">
		<div class="col-sm-12 text-center">
			<h1>Edytuj to ogłoszenie</h1>
		</div>
	</div>
</div>

<!-- FORM ERRORS -->
{% if form.errors %}
	{% for field, errors in form.errors.items %}
		{% for error in errors %}
		    <div class="row">
		        <div class="text-center alert alert-danger">
		            <strong>{{ error }}</strong>
		        </div>
		    </div>
		{% endfor %}
	{% endfor %}
{% endif %}

<!-- REGISTRATION FORM FROM CONTEXT -->
<form method="POST" action="" enctype="multipart/form-data" role="form" class="form-horizontal">
    {% csrf_token %}
    {% for field in form %}
    	<div class="form-group">
    		<label class="control-label col-sm-5" for="{{ field.id_for_label }}">{{ field.label }}</label>
    		<div class="col-sm-2">
    			{% if field.html_name == "photo" %}
    				{{ field | add_class:"file" }}
    			{% else %}
	    			{{ field | add_class:"form-control" }}
	    		{% endif %}
	    	</div>
	    </div>
    {% endfor %}
    <div class="form-group">
	<div class="col-sm-offset-5 col-sm-10">
		<button type="submit" class="btn btn-default">Zmień ogłoszenie</button>
	</div>
</div>
</form>
{% endblock %}

XLO/templates/ads/list.html
{% extends "base.html" %}

{% block title %}
	Lista ogłoszeń
{% endblock %}

{% block content %}
	<div class="container">
	  <h2>Ogłoszenia</h2>
	  <p>Lista aktualnych ogłoszeń:</p>            
	  <table class="table table-hover">
	    <thead>
	      <tr>
	        <th>Tytuł</th>
	        <th>Data dodania</th>
	        <th>Cena</th>
	      </tr>
	    </thead>
	    <tbody>
	      {% for ad in ads_list %}

	      	<tr class="clickable-row" data-href="{{ ad.get_absolute_url }}">
				<td><strong>{{ ad.title }}</strong></td>
				<td>{{ ad.create_date }}</td>
				<td><strong>{{ ad.price }}<strong></td>
				<td class="text-center"><img class="ogloszenie-thumb" src="{{ ad.get_photo_url }}"/></td>
			</tr>
			
		  {% endfor %}
	    </tbody>
	  </table>
	</div>

	<!-- extra JQuery for clickable rows -->
	<script>
		jQuery(document).ready(function($) {
		    $(".clickable-row").click(function() {
		        window.document.location = $(this).data("href");
		    });
		});
	</script>
{% endblock %}
	